In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import GroupKFold
from sklearn.metrics import r2_score
import lightgbm as lgb

In [2]:
df = pd.read_csv('dataset/feature_engineered_train.csv')
df.head()

,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather,...,LargeVehicles_bin,road_score,road_capacity,lane_vehicle_interaction,geohash_mean_demand,weather_mean_demand,geohash_hour_mean,geohash_weather_mean,sin_day,cos_day
0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,16.382587,NaN,...,0,NaN,NaN,0,0.040048,NaN,0.034855,NaN,-0.781831,0.62349
1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny,...,1,1.0,3.0,3,0.208766,0.094247,0.140998,0.211319,-0.781831,0.62349
2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny,...,0,1.0,1.0,0,0.127931,0.094247,0.068046,0.135150,-0.781831,0.62349
3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,16.382587,Rainy,...,0,1.0,1.0,0,0.014381,0.094471,0.011243,0.011382,-0.781831,0.62349
4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy,...,0,1.0,1.0,0,0.029300,0.094471,0.020746,0.021256,-0.781831,0.62349

In [3]:
target = "demand"
groups = df["geohash"]

In [4]:
def oof_target_encoding(df, col, target, n_splits=5):
    gkf = GroupKFold(n_splits=n_splits)
    global_mean = df[target].mean()

    encoded = np.zeros(len(df))

    for train_idx, val_idx in gkf.split(df, groups=df["geohash"]):
        train, val = df.iloc[train_idx], df.iloc[val_idx]

        means = train.groupby(col)[target].mean()
        encoded[val_idx] = df.iloc[val_idx][col].map(means).fillna(global_mean)

    return encoded

In [5]:
df["geohash_te"] = oof_target_encoding(df, "geohash", target)

In [6]:
global_mean = df[target].mean()
geohash_stats = df.groupby("geohash")["demand"].agg(["mean", "count"])

alpha = 10

geohash_te_map = (
    (geohash_stats["mean"] * geohash_stats["count"] + global_mean * alpha)
    / (geohash_stats["count"] + alpha)
).to_dict()

In [21]:
artifacts = {
    "global_mean": global_mean,
    "geohash_stats": geohash_stats,
    "geohash_te_map": geohash_te_map,
    "temp_median": df["Temperature"].median(),
    "geohash_mean": df.groupby("geohash")["demand"].mean(),
    "weather_mean": df.groupby("Weather")["demand"].mean(),
    "geohash_hour_mean": df.groupby(["geohash","hour"])["demand"].mean().to_dict(),
    "geohash_weather_mean": df.groupby(["geohash","Weather"])["demand"].mean().to_dict()
}
artifacts

{'global_mean': np.float64(0.09394238120172715),
 'geohash_stats':              mean  count
 geohash
 qp02yc   0.018498     12
 qp02yf   0.029433      1
 qp02yy   0.002902      2
 qp02yz   0.036564     30
 qp02z1   0.040048     33
 ...           ...    ...
 qp0dn4   0.007811      3
 qp0dn5   0.003714      7
 qp0dnh   0.001401      2
 qp0dnj   0.026414     55
 qp0dnn   0.004244      2

 [1249 rows x 2 columns],
 'geohash_te_map': {'qp02yc': 0.05279070670739287,
  'qp02yf': 0.08807785265819415,
  'qp02yy': 0.078768912789933,
  'qp02yz': 0.05090836483009065,
  'qp02z1': 0.05258130102828422,
  'qp02z3': 0.04113655254737355,
  'qp02z4': 0.06047796347565877,
  'qp02z5': 0.048606357786152105,
  'qp02z6': 0.050964196557133634,
  'qp02z7': 0.051408661717313925,
  'qp02z9': 0.045564354899506596,
  'qp02zc': 0.057355996767405396,
  'qp02zd': 0.06064684414585087,
  'qp02ze': 0.09131732194977638,
  'qp02zf': 0.0672928312052766,
  'qp02zg': 0.05299628190819405,
  'qp02zh': 0.12941341496980646,
  'qp02zj': 0.17615716594643602,
  'qp02zk': 0.0518207776665913,
  'qp02zm': 0.07225369997708987,
  'qp02zn': 0.12843533070007046,
  'qp02zp': 0.0961679772641934,
  'qp02zq': 0.043352457876281655,
  'qp02zr': 0.14387653364142175,
  'qp02zs': 0.074881980073816,
  'qp02zt': 0.1971677453788138,
  'qp02zu': 0.05143974708533625,
  'qp02zv': 0.08424177192654309,
  'qp02zw': 0.4476835978860231,
  'qp02zx': 0.28410933803993954,
  'qp02zy': 0.12940600678828518,
  'qp02zz': 0.3045119376779421,
  'qp03jq': 0.03389929107810584,
  'qp03jr': 0.030242298719501973,
  'qp03jw': 0.03298664655832161,
  'qp03jx': 0.028728458861711992,
  'qp03jy': 0.03710492116096085,
  'qp03jz': 0.033981351863798887,
  'qp03m2': 0.02502713250667647,
  'qp03m3': 0.02318912578403068,
  'qp03m6': 0.06202249362907729,
  'qp03m7': 0.02804147828494831,
  'qp03m8': 0.025986231223978452,
  'qp03m9': 0.028516678505830187,
  'qp03mb': 0.06777100185515414,
  'qp03mc': 0.0368472463530826,
  'qp03md': 0.02334578916420667,
  'qp03me': 0.03811198799952638,
  'qp03mf': 0.03736971967180648,
  'qp03mg': 0.18804630787539575,
  'qp03mk': 0.02463019378226647,
  'qp03mm': 0.022518590580782465,
  'qp03mq': 0.022376351407393264,
  'qp03mr': 0.021952392756019495,
  'qp03ms': 0.02680523707886719,
  'qp03mt': 0.03919715499565095,
  'qp03mu': 0.04911092708126125,
  'qp03mv': 0.04971394080798419,
  'qp03mw': 0.048169882957070774,
  'qp03mx': 0.029730329803613887,
  'qp03my': 0.06357058609119148,
  'qp03mz': 0.05071549103098316,
  'qp03nb': 0.07997733665345777,
  'qp03nd': 0.050017169487929156,
  'qp03nf': 0.08542738540578879,
  'qp03nn': 0.06400175279061628,
  'qp03np': 0.03509824048902004,
  'qp03nq': 0.07915390435382612,
  'qp03nr': 0.054774490707390315,
  'qp03nw': 0.052236924186595125,
  'qp03nx': 0.056693086887395244,
  'qp03ny': 0.07705943308045533,
  'qp03nz': 0.10675467145682775,
  'qp03p0': 0.0435469856955772,
  'qp03p1': 0.04377500468227923,
  'qp03p2': 0.21769854925191925,
  'qp03p3': 0.08437551968704778,
  'qp03p4': 0.04026861715665404,
  'qp03p5': 0.06465829631438734,
  'qp03p6': 0.05879669580102978,
  'qp03p7': 0.2567522076971711,
  'qp03p8': 0.10806292048115018,
  'qp03p9': 0.09344278276048198,
  'qp03pb': 0.13868407604347588,
  'qp03pc': 0.0851269394157899,
  'qp03pd': 0.155429289237214,
  'qp03pe': 0.09522044505152993,
  'qp03pf': 0.061823514983994715,
  'qp03pg': 0.0555129005733341,
  'qp03pk': 0.07013197385204774,
  'qp03pm': 0.045324270688958924,
  'qp03pn': 0.024133586805927518,
  'qp03pp': 0.09191217526561841,
  'qp03pq': 0.03774682817458487,
  'qp03pr': 0.09617740168257692,
  'qp03ps': 0.06630766144517258,
  'qp03pt': 0.06582934867636295,
  'qp03pu': 0.06765379217206731,
  'qp03pv': 0.0489952929553816,
  'qp03pw': 0.03166578550200096,
  'qp03px': 0.05540863980787563,
  'qp03py': 0.02546644642648231,
  'qp03pz': 0.03975786694873157,
  'qp03q0': 0.04509410948150994,
  'qp03q1': 0.053063796583979125,
  'qp03q2': 0.06538312464308843,
  'qp03q3': 0.06221740585278602,
  'qp03q4': 0.09086835381720992,
  'qp03q5': 0.058075919367557606,
  'qp03q6': 0.05337727068444433,
  'qp03q7': 0.04375129790245699,
  'qp03q8': 0.053226102011863605,
  'qp03q9': 0.09522581773056175,
  'qp03qb': 0.08217151563427089,
  'qp03qc': 0.07732538241325655,
  'qp03qd': 0.10193022043170905,
  'qp03qe': 0.08426132906690331,
  'qp03qf': 0.33888850872785875,
  'qp03qg': 0.4627535184417531,
  'qp03qh': 0.05840958694998753,
  'qp03qj': 0.1326635191416686,
  'qp03qk': 0.024824551453876274,
  'qp03qm': 0.1260849241511467,
  'qp03qn': 0.02556170527543079,
  'qp03qp': 0.04571073187968455,
  'qp03qq': 0.04197061759470279,
  'qp03qr': 0.029340295080523607,
  'qp03qs': 0.0938640117817538,
  'qp03qt': 0.07981610019236308,
  'qp03qu': 0.11424453001338189,
  'qp03qv': 0.06485782086605307,
  'qp03qw': 0.03600709165141665,
  'qp03qx': 0.03094429677980419,
  'qp03qy': 0.2040425859974114,
  'qp03qz': 0.03952373046342108,
  'qp03r0': 0.10512412641027517,
  'qp03r1': 0.13769381709411155,
  'qp03r2': 0.2060129599561721,
  'qp03r3': 0.09698714070993997,
  'qp03r4': 0.07896568886511356,
  'qp03r5': 0.07080054644546441,
  'qp03r6': 0.0871798885028216,
  'qp03r7': 0.023959547376586763,
  'qp03r8': 0.056152126055332624,
  'qp03r9': 0.10338845182658256,
  'qp03rb': 0.028774807458435803,
  'qp03rc': 0.025604766200566474,
  'qp03rd': 0.05421320373896531,
  'qp03re': 0.08667430480603269,
  'qp03rf': 0.06378810694016673,
  'qp03rg': 0.05213085116379577,
  'qp03rh': 0.11354960534407672,
  'qp03rj': 0.06702937543834533,
  'qp03rk': 0.06688261921720526,
  'qp03rm': 0.12064362069457081,
  'qp03rn': 0.04031532286511575,
  'qp03rp': 0.05153942026698118,
  'qp03rq': 0.06482870111938359,
  'qp03rr': 0.07528085236696566,
  'qp03rs': 0.03347675564704241,
  'qp03rt': 0.10933806359557227,
  'qp03ru': 0.08662061150085733,
  'qp03rv': 0.10049266960856919,
  'qp03rw': 0.14743769137283802,
  'qp03rx': 0.0718447321541573,
  'qp03ry': 0.10613005084811605,
  'qp03rz': 0.08168700041694611,
  'qp03t2': 0.019743134900655535,
  'qp03t3': 0.026345731163411143,
  'qp03t6': 0.025719102595547,
  'qp03t7': 0.04279787710816488,
  'qp03t8': 0.05044008511328029,
  'qp03t9': 0.07673961536394357,
  'qp03tb': 0.057132203149167116,
  'qp03tc': 0.0851616408054701,
  'qp03td': 0.024816822762628053,
  'qp03te': 0.025045478053282638,
  'qp03tf': 0.03588511357141489,
  'qp03tg': 0.026607452862408097,
  'qp03tk': 0.029908851388400555,
  'qp03tm': 0.02225430701985025,
  'qp03tq': 0.038891497144494906,
  'qp03tr': 0.04053112163790676,
  'qp03ts': 0.05472423858336038,
  'qp03tt': 0.026384495677663322,
  'qp03tu': 0.03714105169069881,
  'qp03tv': 0.032726460527488045,
  'qp03tw': 0.024243511809098416,
  'qp03tx': 0.022811350083440252,
  'qp03ty': 0.034172736505201605,
  'qp03tz': 0.024010431807731127,
  'qp03v2': 0.07307950603175943,
  'qp03v9': 0.027920072860993708,
  'qp03vb': 0.03485669441813234,
  'qp03vc': 0.048199354723431266,
  'qp03vd': 0.04961145819797647,
  'qp03w0': 0.045834849248080366,
  'qp03w1': 0.11462632790698991,
  'qp03w2': 0.024723328549313348,
  'qp03w3': 0.13931023538691167,
  'qp03w4': 0.07572902759355422,
  'qp03w5': 0.0402508058103733,
  'qp03w6': 0.04661639669716666,
  'qp03w7': 0.042290007347516034,
  'qp03w8': 0.17128740394001368,
  'qp03w9': 0.28571728476324004,
  'qp03wb': 0.030240561260632036,
  'qp03wc': 0.22806261661689703,
  'qp03wd': 0.18382121665559012,
  'qp03we': 0.137924344793128,
  'qp03wf': 0.5243817884591946,
  'qp03wg': 0.3888059129039374,
  'qp03wh': 0.036525154617923654,
  'qp03wj': 0.050643073100482695,
  'qp03wk': 0.04363590082369351,
  'qp03wm': 0.07250960245295322,
  'qp03wn': 0.059822549729469515,
  'qp03wp': 0.03154790026658797,
  'qp03wq': 0.05139843342961614,
  'qp03wr': 0.07045056519772278,
  'qp03ws': 0.09947534174529374,
  'qp03wt': 0.06977225697793096,
  'qp03wu': 0.1829665848658712,
  'qp03wv': 0.09607868933398653,
  'qp03ww': 0.06595379977902657,
  'qp03wx': 0.08097042178025476,
  'qp03wy': 0.1416758391331704,
  'qp03wz': 0.30880450405422744,
  'qp03x0': 0.03315516899129143,
  'qp03x1': 0.0993973128310964,
  'qp03x2': 0.08019701638999358,
  'qp03x3': 0.10061256591312283,
  'qp03x4': 0.05925762328615665,
  'qp03x5': 0.17241914846613568,
  'qp03x6': 0.0796629229904106,
  'qp03x7': 0.14825356046410756,
  'qp03x8': 0.08178068497095832,
  'qp03x9': 0.06730958838974278,
  'qp03xb': 0.04761506410064393,
  'qp03xc': 0.052691166544409695,
  'qp03xd': 0.07024805664723167,
  'qp03xe': 0.08917353403185027,
  'qp03xf': 0.12114615880835476,
  'qp03xg': 0.13594467860031037,
  'qp03xh': 0.18516476737281526,
  'qp03xj': 0.20278378864756527,
  'qp03xk': 0.24781396158474206,
  'qp03xm': 0.5335190822794326,
  'qp03xn': 0.13384135530855404,
  'qp03xp': 0.18702561377761584,
  'qp03xq': 0.08327967837820953,
  'qp03xr': 0.09783894576879083,
  'qp03xs': 0.18856804498244453,
  'qp03xt': 0.20941448858667283,
  'qp03xu': 0.11393041351047851,
  'qp03xv': 0.16713158771394832,
  'qp03xw': 0.4015576693507751,
  'qp03xx': 0.5844762634733727,
  'qp03xy': 0.3697865420376694,
  'qp03xz': 0.20742513559509576,
  'qp03y0': 0.022076778443584112,
  'qp03y1': 0.024601845146190408,
  'qp03y2': 0.041446150780191156,
  'qp03y3': 0.026604228174354934,
  'qp03y4': 0.04781938608845157,
  'qp03y5': 0.07895494343523889,
  'qp03y6': 0.036463797724218885,
  'qp03y7': 0.06327627252942694,
  'qp03y8': 0.11289426364140992,
  'qp03y9': 0.08843679256699986,
  'qp03yb': 0.5053436141548938,
  'qp03yc': 0.11175580179596786,
  'qp03yd': 0.09591695754066215,
  'qp03ye': 0.07246865379480756,
  'qp03yf': 0.03610072593675604,
  'qp03yg': 0.19255584098108297,
  'qp03yk': 0.03022067123276858,
  'qp03ym': 0.026256870092658195,
  'qp03yn': 0.08560208706846388,
  'qp03yq': 0.024655748701834818,
  'qp03yr': 0.07849605654312525,
  'qp03ys': 0.10036324207429873,
  'qp03yt': 0.06837865524064878,
  'qp03yu': 0.05576128412422566,
  'qp03yv': 0.0468869324990967,
  'qp03yw': 0.028732745298681573,
  'qp03yx': 0.04430408747403951,
  'qp03yy': 0.0664605666541997,
  'qp03yz': 0.045538626912176215,
  'qp03z0': 0.1423500183754689,
  'qp03z1': 0.033350302801541026,
  'qp03z2': 0.32907676506740763,
  'qp03z3': 0.07286561010634497,
  'qp03z4': 0.04354114624905913,
  'qp03z5': 0.025555257621061835,
  'qp03z6': 0.024443062398031373,
  'qp03z7': 0.02783487834353983,
  'qp03z8': 0.12833571150781684,
  'qp03z9': 0.0917321917056419,
  'qp03zb': 0.18459493244040684,
  'qp03zc': 0.1350128052756128,
  'qp03zd': 0.03951887712485885,
  'qp03ze': 0.033996616836539116,
  'qp03zf': 0.14656918887507658,
  'qp03zg': 0.05990684881745826,
  'qp03zh': 0.039409399728364256,
  'qp03zj': 0.02878812427779931,
  'qp03zk': 0.025366205772363218,
  'qp03zm': 0.024217146029088425,
  'qp03zn': 0.032081102092766954,
  'qp03zp': 0.024084589634341298,
  'qp03zq': 0.03798291076033486,
  'qp03zr': 0.024976183776184654,
  'qp03zs': 0.03083566856908141,
  'qp03zt': 0.21758279391464244,
  'qp03zu': 0.053339350199292215,
  'qp03zv': 0.4344638455059469,
  'qp03zw': 0.029883778755247427,
  'qp03zy': 0.07836782206085799,
  'qp03zz': 0.22997916427602552,
  'qp06n8': 0.026337706518224816,
  'qp06n9': 0.02241754944372277,
  'qp06nb': 0.043201567999561576,
  'qp06nc': 0.03456008602183605,
  'qp06nd': 0.021411440897508436,
  'qp06ne': 0.023165145837636247,
  'qp06nf': 0.030001229226992564,
  'qp06ng': 0.02777697912828696,
  'qp06ns': 0.03693104922134549,
  'qp06nt': 0.03859448197037916,
  'qp06nu': 0.07989929866584033,
  'qp06nv': 0.03349010865023615,
  'qp06ny': 0.03520362340661527,
  'qp06p0': 0.029976080473799918,
  'qp06p1': 0.024575785350769007,
  'qp06p2': 0.03385942589754999,
  'qp06p3': 0.023711834420815772,
  'qp06p4': 0.022322786528632742,
  'qp06p5': 0.08574010747018708,
  'qp06p6': 0.02117409114300976,
  'qp06p7': 0.03052869961274036,
  'qp06p8': 0.036450552921578935,
  'qp06p9': 0.02648814505404149,
  'qp06pb': 0.12321065965388722,
  'qp06pc': 0.02173980668286013,
  'qp06pd': 0.025250954321877968,
  'qp06pe': 0.04470345207201641,
  'qp06pf': 0.025272416413438234,
  'qp06pg': 0.02284847817338099,
  'qp06ph': 0.06872743932981697,
  'qp06pj': 0.021575684791752182,
  'qp06pk': 0.02808425760810849,
  'qp06pm': 0.022483606004774413,
  'qp06pn': 0.03204671937375117,
  'qp06pq': 0.02092125706056358,
  'qp06ps': 0.021017345345228262,
  'qp06pt': 0.020426836359582822,
  'qp06pu': 0.027856919741727864,
  'qp06pv': 0.02114317934787664,
  'qp06pw': 0.024581879471938618,
  'qp06py': 0.04714340836456889,
  'qp08b1': 0.06615669706063218,
  'qp08b4': 0.04514698185458272,
  'qp08b5': 0.0586459857716906,
  'qp08b6': 0.0511291916028776,
  'qp08b7': 0.04378249569661157,
  'qp08bd': 0.054739095100172795,
  'qp08be': 0.04855475741413489,
  'qp08bg': 0.04408526554349049,
  'qp08bh': 0.13656155311499046,
  'qp08bj': 0.12351698308040834,
  'qp08bk': 0.10972731723406413,
  'qp08bm': 0.06373932838968982,
  'qp08bn': 0.08011175270647282,
  'qp08bp': 0.05223503060865073,
  'qp08bq': 0.052302940322806815,
  'qp08br': 0.07151960401920034,
  'qp08bs': 0.04638966441571864,
  'qp08bt': 0.08547308910794581,
  'qp08bu': 0.04887157880904125,
  'qp08bv': 0.05352867097289732,
  'qp08bw': 0.05436569786236,
  'qp08bx': 0.04719006508100475,
  'qp08by': 0.12841834493443202,
  'qp08bz': 0.10632045395966276,
  'qp08c5': 0.05432010602971237,
  'qp08cj': 0.05286291782837724,
  'qp08ck': 0.05434938143197744,
  'qp08cm': 0.08808734161238226,
  'qp08cn': 0.06406295518053837,
  'qp08cp': 0.13705938641918003,
  'qp08cv': 0.08563690583356656,
  'qp08cy': 0.04167694072565437,
  'qp08fh': 0.07264373929076617,
  'qp08fj': 0.07441785581106093,
  'qp08fn': 0.07881215119415906,
  'qp08fp': 0.07371614337030699,
  'qp08fq': 0.08567433724444493,
  'qp08fr': 0.0549887104654298,
  'qp08fv': 0.03703656197946013,
  'qp08fw': 0.05014482353168877,
  'qp08fx': 0.03308439988904533,
  'qp08fy': 0.035041153455022594,
  'qp08fz': 0.029049144338978587,
  'qp08g5': 0.07310279765536293,
  'qp08g6': 0.0738799957409221,
  'qp08g7': 0.08557066801015578,
  'qp08gh': 0.08583009713326518,
  'qp08gj': 0.049973206413786865,
  'qp08gk': 0.04724416949499938,
  'qp08gm': 0.04388618630030243,
  'qp08gn': 0.03757220313337483,
  'qp08gp': 0.034276307094545315,
  'qp08gq': 0.04653482239578362,
  'qp08gr': 0.05562059902281249,
  'qp08gs': 0.08599840452164997,
  'qp08gt': 0.029681268660520448,
  'qp08gu': 0.07257449930605378,
  'qp08gv': 0.04891233025391055,
  'qp08gw': 0.04116898070236298,
  'qp08gx': 0.045712858206178736,
  'qp08gy': 0.032791832626925976,
  'qp08gz': 0.06268330069617063,
  'qp08uj': 0.07988888146163262,
  'qp08un': 0.03069823306548294,
  'qp08up': 0.06700671297824996,
  'qp0900': 0.28611528612966636,
  'qp0901': 0.044141906794403905,
  'qp0902': 0.10461709273891118,
  'qp0903': 0.04677306063131751,
  'qp0904': 0.17311418893977798,
  'qp0905': 0.07270504534486397,
  'qp0906': 0.05790369636956701,
  'qp0907': 0.23346978425108836,
  'qp0908': 0.04311845993477559,
  'qp0909': 0.06926231042891667,
  'qp090b': 0.2730753313678015,
  'qp090c': 0.20705366068121187,
  'qp090d': 0.05709013615849008,
  'qp090e': 0.2506110207922576,
  'qp090h': 0.08404978824509042,
  'qp090j': 0.039931093043445255,
  'qp090k': 0.17150928087216835,
  'qp090m': 0.1281447382539315,
  'qp090n': 0.02390765635985124,
  'qp090p': 0.026307168296576876,
  'qp090q': 0.029317353194479857,
  'qp090r': 0.05113185280384708,
  'qp090s': 0.23317412832304257,
  'qp090t': 0.31180374027012653,
  'qp090v': 0.0689869029054431,
  'qp090w': 0.04187336235879216,
  'qp090x': 0.04537973945582783,
  'qp090y': 0.055286973353208986,
  'qp090z': 0.08624885721672479,
  'qp0917': 0.08555680197633374,
  'qp091e': 0.05164412587402343,
  'qp091g': 0.042013086577253146,
  'qp091k': 0.06269626732094138,
  'qp091m': 0.06260844472077354,
  'qp091q': 0.04431521829307834,
  'qp091r': 0.04283800929587089,
  'qp091s': 0.06462990119801253,
  'qp091t': 0.07930560009054459,
  'qp091u': 0.0341973028742712,
  'qp091v': 0.033136231137526964,
  'qp091w': 0.032518881261395176,
  'qp091x': 0.04553822136286454,
  'qp091y': 0.05964690711489088,
  'qp091z': 0.10290426515430577,
  'qp0920': 0.06833374068319005,
  'qp0921': 0.0719569823452563,
  'qp0922': 0.025113289398888815,
  'qp0923': 0.0230310452251394,
  'qp0924': 0.059445417478103106,
  'qp0925': 0.15864576328679644,
  'qp0926': 0.06993164028928923,
  'qp0927': 0.1782152132983977,
  'qp0928': 0.04013568793344064,
  'qp0929': 0.05056734210429881,
  'qp092d': 0.04997855122602789,
  'qp092e': 0.05796722593467681,
  'qp092h': 0.13392765026260844,
  'qp092j': 0.15846344653392885,
  'qp092k': 0.15548635755641738,
  'qp092m': 0.17997919012884478,
  'qp092n': 0.16473562103505449,
  'qp092p': 0.07210224903669951,
  'qp092q': 0.18669427302484498,
  'qp092r': 0.1021939675586977,
  'qp092s': 0.051256581212966015,
  'qp092t': 0.06829874816790006,
  'qp092w': 0.15943424302721415,
  'qp092x': 0.08438454939650389,
  'qp092z': 0.08658834293720302,
  'qp0930': 0.046466174361010464,
  'qp0931': 0.0858650381728725,
  'qp0932': 0.035141764677725534,
  'qp0933': 0.035669075855715514,
  'qp0934': 0.07368898102535787,
  'qp0936': 0.029979857959729725,
  'qp0937': 0.07346760330619784,
  'qp0938': 0.06544997223997769,
  'qp093b': 0.07057305253626167,
  'qp093c': 0.04356958103584724,
  'qp093d': 0.04606510809072534,
  'qp093e': 0.03376691690616529,
  'qp093f': 0.041646275887950744,
  'qp093g': 0.04721071551172107,
  'qp093h': 0.08547628980302636,
  'qp093j': 0.06941224981533949,
  'qp093k': 0.08608353778578458,
  'qp093m': 0.05990570289395161,
  'qp093n': 0.0739276614578367,
  'qp093p': 0.03444045714657318,
  'qp093q': 0.035199404746868015,
  'qp093r': 0.08758112521072786,
  'qp093s': 0.03272839512866617,
  'qp093t': 0.03256493640681303,
  'qp093u': 0.04811366639936269,
  'qp093v': 0.04782828439265118,
  'qp093w': 0.12689450358029636,
  'qp093x': 0.13842472601619887,
  'qp093y': 0.07976713521280489,
  'qp093z': 0.03419161301772738,
  'qp0941': 0.04776323147432552,
  'qp0942': 0.07953922501917278,
  'qp0943': 0.07359795913595704,
  'qp0944': 0.04206637555458028,
  'qp0945': 0.06744192025674291,
  'qp0946': 0.03699992745265411,
  'qp0947': 0.052370212622342836,
  'qp0948': 0.03434185312937403,
  'qp0949': 0.03658426717539113,
  'qp094b': 0.05703563434914133,
  'qp094c': 0.05511211695865004,
  'qp094d': 0.03263384992745295,
  'qp094e': 0.03762967578087527,
  'qp094f': 0.07466093361156376,
  'qp094g': 0.03502166138413568,
  'qp094h': 0.033448074533839064,
  'qp094j': 0.030902686638873154,
  'qp094k': 0.04669998002202912,
  'qp094m': 0.04287691851399482,
  'qp094n': 0.20552783630147414,
  'qp094p': 0.04656256603414499,
  'qp094q': 0.17532225831248618,
  'qp094r': 0.333400355211507,
  'qp094s': 0.03426087451942544,
  'qp094t': 0.05569041074911882,
  'qp094u': 0.04014230135077727,
  'qp094v': 0.029016259181925366,
  'qp094w': 0.04579859619686859,
  'qp094x': 0.08933652936841206,
  'qp094y': 0.040833252290732897,
  'qp094z': 0.031323746297295466,
  'qp0950': 0.25371896606960875,
  'qp0951': 0.05983595147559092,
  'qp0952': 0.05333163581113546,
  'qp0953': 0.07085661330035825,
  'qp0954': 0.0705899516042519,
  'qp0956': 0.07872979488841526,
  'qp0957': 0.03539973669063446,
  'qp0958': 0.05077024861863114,
  'qp0959': 0.03786751700862013,
  'qp095b': 0.03746084797930891,
  'qp095c': 0.04277390609641516,
  'qp095d': 0.03737220104251419,
  'qp095e': 0.02841351922928548,
  'qp095f': 0.06038799141799038,
  'qp095g': 0.06884519853737117,
  'qp095h': 0.0795598046910989,
  'qp095j': 0.03305581708039762,
  'qp095k': 0.03653657525670254,
  'qp095m': 0.03422484926697966,
  'qp095n': 0.04042223626596295,
  'qp095p': 0.04257726227007718,
  'qp095q': 0.08566019571150695,
  'qp095r': 0.09258701893291704,
  'qp095s': 0.03349619822765156,
  'qp095t': 0.02471166033039999,
  'qp095u': 0.038030087311681164,
  'qp095v': 0.0939451872522703,
  'qp095w': 0.06279718195845668,
  'qp095x': 0.05081631899671447,
  'qp095y': 0.027769325207871752,
  'qp095z': 0.05019925603328878,
  'qp0960': 0.05309053461935387,
  'qp0961': 0.07174055939707852,
  'qp0962': 0.09776371627510921,
  'qp0963': 0.03741076247932147,

In [22]:
features = [
    # time
    "sin_time", "cos_time",
    "sin_day", "cos_day",
    "hour",

    # weather
    "Temperature",
    "temp_sq",
    "weather_temp",
    "temp_bin",

    # infrastructure
    "NumberofLanes",
    "road_capacity",
    "road_score",
    "Landmarks_bin",
    "LargeVehicles_bin",
    "lane_vehicle_interaction",

    # categorical
    "RoadType",
    "Weather",
    "demand_period",
    "time_bucket",

    # spatial
    "geohash_te",

    "geohash_mean_demand",
    "weather_mean_demand",
    "geohash_hour_mean",
    "geohash_weather_mean"
]

In [23]:
cat_cols = ["RoadType", "Weather", "temp_bin", "demand_period", "time_bucket", "weather_temp"]

for c in cat_cols:
    df[c] = df[c].astype("category")

In [24]:
params = {
    "objective": "regression",
    "metric": "rmse",
    "learning_rate": 0.03,
    "num_leaves": 128,
    "max_depth": -1,
    "min_data_in_leaf": 30,
    "feature_fraction": 0.85,
    "bagging_fraction": 0.8,
    "bagging_freq": 5,
    "lambda_l2": 1.0,
    "verbosity": -1
}

In [25]:
x = df[features].copy()
y = df["demand"]

In [26]:
gkf = GroupKFold(n_splits=5)

oof_preds = np.zeros(len(df))

for fold, (train_idx, val_idx) in enumerate(gkf.split(x, y, groups=df["geohash"])):

    x_train, x_val = x.iloc[train_idx], x.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    train_data = lgb.Dataset(
        x_train,
        label=y_train,
        categorical_feature=cat_cols
    )

    val_data = lgb.Dataset(
        x_val,
        label=y_val,
        categorical_feature=cat_cols
    )

    model = lgb.train(
        params,
        train_data,
        valid_sets=[val_data],
        num_boost_round=5000,
        callbacks=[lgb.early_stopping(200)]
    )

    preds = model.predict(x_val)
    oof_preds[val_idx] = preds

    print("Fold R2:", r2_score(y_val, preds))

Training until validation scores don't improve for 200 rounds
Early stopping, best iteration is:
[395]	valid_0's rmse: 0.0240698
Fold R2: 0.9708730575987792
Training until validation scores don't improve for 200 rounds
Early stopping, best iteration is:
[254]	valid_0's rmse: 0.0227612
Fold R2: 0.9668317183990752
Training until validation scores don't improve for 200 rounds
Early stopping, best iteration is:
[290]	valid_0's rmse: 0.0243531
Fold R2: 0.9674249353867411
Training until validation scores don't improve for 200 rounds
Early stopping, best iteration is:
[327]	valid_0's rmse: 0.0229866
Fold R2: 0.9702518986756538
Training until validation scores don't improve for 200 rounds
Early stopping, best iteration is:
[220]	valid_0's rmse: 0.0268541
Fold R2: 0.9754477225518415

In [27]:
print("OOF R2:", r2_score(y, oof_preds))

OOF R2: 0.9709167052428966

In [28]:
import joblib
joblib.dump(artifacts, "artifacts.pkl")
joblib.dump(model, "model.pkl")

['model.pkl']

In [29]:
test = pd.read_csv('dataset/test.csv', index_col='Index')
test.head()

,geohash,day,timestamp,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
Index,,,,,,,,,
0,qp02z1,49,2:15,NaN,1,Not Allowed,No,NaN,NaN
1,qp02z9,49,2:15,Residential,1,Not Allowed,No,6.476213,Snowy
2,qp02yf,49,2:15,Residential,3,Allowed,Yes,22.318203,Sunny
3,qp02z6,49,2:15,Residential,2,Not Allowed,Yes,NaN,Rainy
4,qp02zd,49,2:15,Residential,1,Not Allowed,No,18.266162,Foggy

In [35]:
class DemandFeaturePipeline:
    
    def __init__(self, artifacts):
        """
        artifacts = dict containing all training-time statistics
        """
        self.global_mean = artifacts["global_mean"]
        self.geohash_te_map = artifacts["geohash_te_map"]
        self.temp_median = artifacts["temp_median"]
        self.geohash_mean = artifacts["geohash_mean"]
        self.weather_mean = artifacts["weather_mean"]
        self.geohash_hour_mean = artifacts["geohash_hour_mean"]
        self.geohash_weather_mean = artifacts["geohash_weather_mean"]
        
        self.road_map = {
            'Highway':3,
            'Street':2,
            'Residential':1
        }

        self.cat_cols = [
            "RoadType",
            "Weather",
            "temp_bin",
            "demand_period",
            "time_bucket",
            "weather_temp"
        ]

    def transform(self, df):

        df = df.copy()

        # ---------------------------
        # 1. Clean categorical cols
        # ---------------------------
        cat_cols_raw = [
            'geohash','RoadType','LargeVehicles',
            'Landmarks','Weather'
        ]

        for c in cat_cols_raw:
            df[c] = df[c].astype(str).str.strip()

        # ---------------------------
        # 2. Missing flags
        # ---------------------------
        df['temp_missing'] = df['Temperature'].isna().astype(int)
        df['weather_missing'] = df['Weather'].isna().astype(int)
        df['roadtype_missing'] = df['RoadType'].isna().astype(int)

        # ---------------------------
        # 3. Fill temperature
        # ---------------------------
        df['Temperature'] = df['Temperature'].fillna(self.temp_median)

        # ---------------------------
        # 4. Time parsing
        # ---------------------------
        df[['hour','minute']] = df['timestamp'].apply(
            lambda x: pd.Series(list(map(int, x.split(':'))))
        )

        df['total_minutes'] = df['hour'] * 60 + df['minute']

        df['sin_time'] = np.sin(2*np.pi*df['total_minutes']/1440)
        df['cos_time'] = np.cos(2*np.pi*df['total_minutes']/1440)

        # ---------------------------
        # 5. Time buckets
        # ---------------------------
        def get_time_bucket(h):
            if h < 6: return 'Night'
            elif h < 12: return 'Morning'
            elif h < 18: return 'Afternoon'
            return 'Evening'

        df['time_bucket'] = df['hour'].apply(get_time_bucket)

        def demand_period(h):
            if h <= 4: return "Night"
            elif h <= 9: return "MorningRise"
            elif h <= 14: return "Peak"
            elif h <= 17: return "Decline"
            elif h <= 20: return "LowDemand"
            return "Recovery"

        df['demand_period'] = df['hour'].apply(demand_period)

        # ---------------------------
        # 6. Temperature bins
        # ---------------------------
        df['temp_bin'] = pd.cut(
            df['Temperature'],
            bins=[-np.inf,10,20,30,40,np.inf],
            labels=['VeryCold','Cold','Moderate','Warm','Hot']
        )

        df['temp_sq'] = df['Temperature'] ** 2

        # ---------------------------
        # 7. Weather interaction
        # ---------------------------
        df['weather_temp'] = (
            df['Weather'].astype(str) + '_' + df['temp_bin'].astype(str)
        )

        # ---------------------------
        # 8. Binary encodings
        # ---------------------------
        df['Landmarks_bin'] = df['Landmarks'].map({'Yes':1,'No':0})
        df['LargeVehicles_bin'] = df['LargeVehicles'].map({'Allowed':1,'Not Allowed':0})

        # ---------------------------
        # 9. Road features
        # ---------------------------
        df['road_score'] = df['RoadType'].map(self.road_map)
        df['road_capacity'] = df['road_score'] * df['NumberofLanes']
        df['lane_vehicle_interaction'] = df['NumberofLanes'] * df['LargeVehicles_bin']

        # ---------------------------
        # 10. Cyclic day
        # ---------------------------
        df['sin_day'] = np.sin(2*np.pi*df['day']/7)
        df['cos_day'] = np.cos(2*np.pi*df['day']/7)

        # ---------------------------
        # 11. SAFE target encodings (NO RECOMPUTE)
        # ---------------------------
        df['geohash_mean_demand'] = df['geohash'].map(self.geohash_mean)
        df['weather_mean_demand'] = df['Weather'].map(self.weather_mean)

        df['geohash_hour_mean'] = list(
            map(
                lambda x: self.geohash_hour_mean.get(x, self.geohash_mean.get(x[0], 0)),
                zip(df['geohash'], df['hour'])
            )
        )

        df['geohash_weather_mean'] = list(
            map(
                lambda x: self.geohash_weather_mean.get(x, self.geohash_mean.get(x[0], 0)),
                zip(df['geohash'], df['Weather'])
            )
        )

        df["geohash_te"] = df["geohash"].map(self.geohash_te_map)
        df["geohash_te"] = df["geohash_te"].fillna(self.global_mean)

        # ---------------------------
        # 13. Final type casting
        # ---------------------------
        for c in self.cat_cols:
            df[c] = df[c].astype('category')

        return df

In [36]:
class DemandModel:
    
    def __init__(self, model, pipeline, features):
        self.model = model
        self.pipeline = pipeline
        self.features = features

    def predict(self, df):

        df = self.pipeline.transform(df)
        X = df[self.features]

        preds = self.model.predict(X)

        return preds

In [37]:
pipeline = DemandFeaturePipeline(artifacts)

In [38]:
model_wrapper = DemandModel(
    model=model,
    pipeline=pipeline,
    features=features
)

In [39]:
preds = model_wrapper.predict(test)

In [40]:
preds

array([0.07091149, 0.01196211, 0.03442036, ..., 0.01103827, 0.1244087 ,
       0.02170877], shape=(41778,))

In [41]:
test["preds"] = preds
test.head()

,geohash,day,timestamp,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather,preds
Index,,,,,,,,,,
0,qp02z1,49,2:15,NaN,1,Not Allowed,No,NaN,NaN,0.070911
1,qp02z9,49,2:15,Residential,1,Not Allowed,No,6.476213,Snowy,0.011962
2,qp02yf,49,2:15,Residential,3,Allowed,Yes,22.318203,Sunny,0.034420
3,qp02z6,49,2:15,Residential,2,Not Allowed,Yes,NaN,Rainy,0.079664
4,qp02zd,49,2:15,Residential,1,Not Allowed,No,18.266162,Foggy,0.068133

In [43]:
test.to_csv("dataset/submission.csv", columns=["preds"], index_label="Index")